name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, zip, gd, curl, bcmath, intl
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e 'CREATE DATABASE IF NOT EXISTS testing;'

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: testing
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, zip, gd, curl, bcmath, intl

    - name: Install Dependencies
      run: composer install --optimize-autoloader --no-dev

    - name: Create deployment artifact
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *

    - name: Store artifact for distribution
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: ${{ github.sha }}.tar.gz

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        port: ${{ secrets.DO_PORT }}
        script_stop: true
        script: |
          cd /var/www/esimtel
          
          # Create basic structure if first deployment
          mkdir -p releases
          
          # Download latest build using wget (simpler approach)
          RELEASE_DIR="releases/${{ github.sha }}"
          mkdir -p "$RELEASE_DIR"
          
          # Create tar from GitHub
          cd "$RELEASE_DIR"
          git clone https://github.com/yaysoft-ltd/esim-backend.git .
          git checkout ${{ github.sha }}
          rm -rf .git
          
          # Copy environment file
          cd /var/www/esimtel
          cp .env "$RELEASE_DIR/.env"
          
          # Set permissions
          chown -R www-data:www-data "$RELEASE_DIR"
          chmod -R 755 "$RELEASE_DIR"
          chmod -R 775 "$RELEASE_DIR/storage" "$RELEASE_DIR/bootstrap/cache"
          
          # Install dependencies and optimize
          cd "$RELEASE_DIR"
          composer install --optimize-autoloader --no-dev --no-interaction
          php artisan key:generate --force
          php artisan config:cache
          php artisan route:cache  
          php artisan view:cache
          php artisan storage:link
          
          # Run migrations
          php artisan migrate --force
          
          # Switch to new release (zero-downtime)
          cd /var/www/esimtel
          ln -nfs "$RELEASE_DIR" current
          ln -nfs current public_html
          
          # Restart services
          supervisorctl restart laravel-worker:* || true
          systemctl reload nginx
          
          # Cleanup old releases (keep last 3)
          cd releases
          ls -t | tail -n +4 | xargs rm -rf